  APIAPP1.cpp
APIAPP1.obj : error LNK2019: _mysql_init@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
APIAPP1.obj : error LNK2019: _mysql_real_connect@32_main 함수에서 참조되는 확인할 수 없는 외부 기호
APIAPP1.obj : error LNK2019: _mysql_query@8_main 함수에서 참조되는 확인할 수 없는 외부 기호
APIAPP1.obj : error LNK2019: _mysql_store_result@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
APIAPP1.obj : error LNK2019: _mysql_free_result@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
APIAPP1.obj : error LNK2019: _mysql_fetch_row@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
APIAPP1.obj : error LNK2019: _mysql_close@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
C:\Users\직업능력개발훈련 401호_8번\source\repos\APIAPP\Debug\APIAPP0.exe : fatal error LNK1120: 7개의 확인할 수 없는 외부 참조입니다.
